param(
    [ValidateSet("dev", "prod", "local", "cloud", "status", "")]
    [string]$Target = ""
)

$ErrorActionPreference = "Continue"

$PROD_URL = "https://ai-2d-checker-backend.onrender.com"
$PROD_TOKEN = "kmti-cloud-token-2026-secret"
$DEV_URL = "http://127.0.0.1:8080"
$ENV_LOCAL_PATH = Join-Path $PSScriptRoot "apps\desktop\.env.local"

function Show-Header {
    Write-Host "=====================================================" -ForegroundColor Magenta
    Write-Host "       AI-2D-Checker Backend Switcher Utility        " -ForegroundColor Magenta
    Write-Host "=====================================================" -ForegroundColor Magenta
}

function Get-CurrentConfig {
    $currentUrl = $DEV_URL
    $currentToken = ""
    if (Test-Path $ENV_LOCAL_PATH) {
        $content = Get-Content $ENV_LOCAL_PATH -Raw
        if ($content -match 'VITE_BACKEND_URL=(.+)') {
            $currentUrl = $Matches[1].Trim()
        }
        if ($content -match 'VITE_REMOTE_API_TOKEN=(.+)') {
            $currentToken = $Matches[1].Trim()
        }
    }
    return @{
        Url = $currentUrl
        Token = $currentToken
        IsProd = ($currentUrl -like "*onrender.com*")
    }
}

function Test-BackendHealth([string]$Url, [string]$Label) {
    Write-Host "Testing $Label ($Url)..." -NoNewline -ForegroundColor Gray
    try {
        $healthUrl = "$Url/health"
        $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
        $resp = Invoke-RestMethod -Uri $healthUrl -Method Get -TimeoutSec 35 -ErrorAction Stop
        $stopwatch.Stop()
        $latency = [math]::Round($stopwatch.Elapsed.TotalMilliseconds)
        
        if ($resp.status -eq "healthy") {
            Write-Host " [ONLINE] " -ForegroundColor Green -NoNewline
            Write-Host "(${latency}ms, version: $($resp.version), db: $($resp.services.mongodb))" -ForegroundColor DarkGray
        } else {
            Write-Host " [DEGRADED] " -ForegroundColor Yellow -NoNewline
            Write-Host "(${latency}ms, services: $($resp.services | ConvertTo-Json -Compress))" -ForegroundColor DarkGray
        }
    } catch {
        Write-Host " [OFFLINE] " -ForegroundColor Red -NoNewline
        Write-Host "($($_.Exception.Message))" -ForegroundColor DarkGray
    }
}

function Set-ProdBackend {
    Write-Host "`nSwitching target to PROD (Render Cloud)..." -ForegroundColor Cyan
    $envContent = @"
# Generated by switch_backend.ps1
VITE_BACKEND_URL=$PROD_URL
VITE_REMOTE_API_TOKEN=$PROD_TOKEN
"@
    Set-Content -Path $ENV_LOCAL_PATH -Value $envContent -Force
    Write-Host "✅ Active Desktop Backend: $PROD_URL" -ForegroundColor Green
    Write-Host "✅ Pre-configured Token  : $PROD_TOKEN" -ForegroundColor Green
    Write-Host "Config saved to: apps\desktop\.env.local`n" -ForegroundColor DarkGray
    Test-BackendHealth -Url $PROD_URL -Label "Prod Cloud"
}

function Set-DevBackend {
    Write-Host "`nSwitching target to DEV (Local Sidecar)..." -ForegroundColor Cyan
    if (Test-Path $ENV_LOCAL_PATH) {
        Remove-Item -Path $ENV_LOCAL_PATH -Force -ErrorAction SilentlyContinue
    }
    Write-Host "✅ Active Desktop Backend: $DEV_URL (Local Machine)" -ForegroundColor Green
    Write-Host "✅ Token Handling        : Dynamic local encryption via storage/secure/" -ForegroundColor Green
    Write-Host "Removed custom overrides from apps\desktop\.env.local`n" -ForegroundColor DarkGray
    Test-BackendHealth -Url $DEV_URL -Label "Dev Local"
}

function Show-Status {
    $cfg = Get-CurrentConfig
    Write-Host "`n--- Current Configuration ---" -ForegroundColor Yellow
    if ($cfg.IsProd) {
        Write-Host "Active Target: " -NoNewline
        Write-Host "PROD (Render Cloud)" -ForegroundColor Cyan
        Write-Host "Backend URL  : $($cfg.Url)" -ForegroundColor White
        Write-Host "API Token    : $($cfg.Token)" -ForegroundColor White
    } else {
        Write-Host "Active Target: " -NoNewline
        Write-Host "DEV (Local Sidecar)" -ForegroundColor Green
        Write-Host "Backend URL  : $($cfg.Url)" -ForegroundColor White
        Write-Host "API Token    : [Local Decrypted]" -ForegroundColor White
    }
    Write-Host ""
    Test-BackendHealth -Url $DEV_URL -Label "Local Dev"
    Test-BackendHealth -Url $PROD_URL -Label "Render Cloud"
    Write-Host ""
}

Show-Header

if ([string]::IsNullOrWhiteSpace($Target)) {
    Show-Status
    Write-Host "Select Backend Target:" -ForegroundColor Yellow
    Write-Host "  [1] Prod  - Render Cloud ($PROD_URL)" -ForegroundColor Cyan
    Write-Host "  [2] Dev   - Local Sidecar ($DEV_URL)" -ForegroundColor Green
    Write-Host "  [3] Status - Check health only" -ForegroundColor White
    Write-Host "  [Q] Quit" -ForegroundColor DarkGray
    $choice = Read-Host "`nEnter selection (1/2/3/Q)"
    switch ($choice) {
        "1" { Set-ProdBackend }
        "2" { Set-DevBackend }
        "3" { Show-Status }
        default { Write-Host "Exiting without changes." -ForegroundColor DarkGray }
    }
} else {
    switch ($Target.ToLower()) {
        "prod"  { Set-ProdBackend }
        "cloud" { Set-ProdBackend }
        "dev"   { Set-DevBackend }
        "local" { Set-DevBackend }
        "status" { Show-Status }
    }
}
