/**
 * How the PDF export decides where the drawing sits on the page.
 *
 * ## `render_bounds` is not the drawing's extent
 *
 * It comes from `dxf_background_renderer.py`:
 *
 * ```python
 * # Extract the exact tight bounds generated by Matplotlib's autoscale
 * xmin, xmax = ax.get_xlim()
 * ```
 *
 * They are not tight, and the comment saying so is the reason it went unnoticed for so long.
 * `get_xlim()` returns the autoscaled limits, which carry Matplotlib's default `axes.xmargin`
 * / `axes.ymargin` of 5% per side — and `set_aspect('equal', 'box')` then expands whichever axis
 * is short of the figure's ratio, adding more. So every sheet in the system has roughly 10% of
 * dead space baked into its bounds, in the axis that is expanded rather more.
 *
 * Fitting the export to those bounds put that dead space on the page, where it read as an
 * enormous margin no page setting could reach: a 7 mm page margin around a drawing that was
 * already floating inside its own bounds by ~14 mm a side.
 *
 * `render_bounds` itself must not be "fixed". Every zone template stores its boxes as
 * fractions of it, `zone_signature` derives a sheet's template identity from it, and every stored
 * `CadPoint` carries a snapshot of it for drift detection. Re-deriving it would silently
 * invalidate all three. The export crops to the ink instead, which is a question only the export
 * asks.
 */

/**
 * Breathing room around the fitted content, as a fraction of the capture's width.
 *
 * Not zero: the fit rectangle is measured to the outermost *painted pixel*, and a stroke whose
 * centreline sits on that boundary has already had half its width measured — but arrowheads,
 * text antialiasing and the marker glyphs are drawn with their own joins and caps, and a hard
 * edge on a printed sheet reads as a mistake. ~0.4% is a hairline at every size this is used at.
 */
export const EXPORT_PADDING_FRACTION = 0.004;
const MIN_EXPORT_PADDING_PX = 2;

/** A rectangle in fit space: `[x0, y0, x1, y1]`, Y already flipped into canvas direction. */
export type FitRect = [number, number, number, number];

export interface ExportFit {
  scale: number;
  transX: number;
  transY: number;
  padding: number;
}

/**
 * The transform that places `rect` centred inside a `renderWidth` x `renderHeight` capture.
 *
 * Aspect-preserving: the shorter axis is centred, never stretched. Extracted from
 * `CanvasRenderer.renderContent` so the two-pass export can *invert* it — pass one needs to turn
 * painted pixels back into fit-space coordinates, and doing that against a second copy of this
 * arithmetic is how the crop would end up one padding-width off.
 */
export function computeExportFit(
  rect: FitRect,
  renderWidth: number,
  renderHeight: number,
): ExportFit {
  const [x0, y0, x1, y1] = rect;
  const w = x1 - x0;
  const h = y1 - y0;
  const padding = Math.max(
    MIN_EXPORT_PADDING_PX,
    Math.round(renderWidth * EXPORT_PADDING_FRACTION),
  );
  const innerW = renderWidth - 2 * padding;
  const innerH = renderHeight - 2 * padding;
  const scale = Math.min(innerW / w, innerH / h);
  return {
    scale,
    transX: padding + (innerW - w * scale) / 2 - x0 * scale,
    transY: padding + (innerH - h * scale) / 2 - y0 * scale,
    padding,
  };
}

/** Canvas pixel -> fit space, the inverse of {@link computeExportFit}. */
export function fitSpaceFromPixels(
  fit: ExportFit,
  px: number,
  py: number,
): { x: number; y: number } {
  return { x: (px - fit.transX) / fit.scale, y: (py - fit.transY) / fit.scale };
}

/**
 * The bounding box of everything painted onto a white export canvas, in canvas pixels.
 *
 * `null` when the canvas is entirely white — which is a real state, not an error: a drawing whose
 * layers have not loaded yet paints nothing, and the caller must keep its original fit rather
 * than crop to an empty rectangle.
 *
 * Reads the bitmap rather than the entity list on purpose. The question is "what is visible on
 * this page", and the answer has to include the manual markings, annotation pins and marker
 * labels — none of which are entities, all of which must be inside the printed area. It also
 * means the crop cannot disagree with the renderer about culling, because it is measuring the
 * renderer's own output.
 */
export function findInkBounds(
  ctx: CanvasRenderingContext2D,
  width: number,
  height: number,
): FitRect | null {
  const data = ctx.getImageData(0, 0, width, height).data;
  // One 32-bit compare per pixel instead of four 8-bit ones. Opaque white is 0xFFFFFFFF in
  // either byte order, so this needs no endianness handling.
  const px = new Uint32Array(data.buffer);
  const WHITE = 0xffffffff;

  let minX = width;
  let minY = -1;
  let maxX = -1;
  let maxY = -1;

  for (let y = 0; y < height; y++) {
    const row = y * width;
    let rowMin = -1;
    for (let x = 0; x < width; x++) {
      if (px[row + x] !== WHITE) {
        rowMin = x;
        break;
      }
    }
    if (rowMin === -1) continue;

    let rowMax = rowMin;
    for (let x = width - 1; x > rowMin; x--) {
      if (px[row + x] !== WHITE) {
        rowMax = x;
        break;
      }
    }

    if (minY === -1) minY = y;
    maxY = y;
    if (rowMin < minX) minX = rowMin;
    if (rowMax > maxX) maxX = rowMax;
  }

  if (maxY === -1) return null;
  // +1 on the far edges: a pixel index is the box's inside, and the rectangle has to contain it.
  return [minX, minY, maxX + 1, maxY + 1];
}

/**
 * Whether a crop is worth a second full-resolution render.
 *
 * The pass is skipped when the ink already reaches the padded content area, which is the normal
 * case for a drawing whose bounds happen to be tight. 1.5% of the capture is below what survives
 * being printed, and a re-render costs a few hundred milliseconds on the main thread.
 */
export function cropIsWorthwhile(
  ink: FitRect,
  renderWidth: number,
  renderHeight: number,
  padding: number,
): boolean {
  const slack = Math.max(
    ink[0] - padding,
    ink[1] - padding,
    renderWidth - padding - ink[2],
    renderHeight - padding - ink[3],
  );
  return slack > renderWidth * 0.015;
}

/**
 * The notional CSS-pixel width the canvas's pixel sizes are designed against.
 *
 * `resolutionMultiplier` converts those design pixels into capture pixels, and it used to be
 * `renderWidth / width` — where `width` is however wide flexlayout happened to make the canvas
 * panel. On screen that is 1 and correct. On EXPORT it made the printed weight of every stroke,
 * checkmark, card and pin a function of the user's window: the same audit exported from a
 * maximised window and a narrow one came out with different line weights, and neither was wrong
 * in a way anyone could name.
 *
 * 700 is the width this layout typically gives a canvas pane on a 1920-wide display, so an export
 * from an ordinary window is unchanged by pinning it; what changes is that an unusual one now
 * matches. At the report's A4 capture (3492 px across 291 mm) it puts a hairline at ~0.42 mm
 * on paper — heavier than a plotter's 0.13–0.25 mm, and the number to change if these come out
 * looking too bold. It is deliberately the ONE knob: raising it thins every line on the page
 * together.
 */
export const EXPORT_REFERENCE_WIDTH_PX = 700;

/**
 * Design pixels -> pass pixels.
 *
 * A pure function so the window-independence is assertable. It is the whole fix: on export the
 * denominator is a constant, not the panel's width.
 */
export function resolutionMultiplierFor(
  isExport: boolean,
  renderWidth: number,
  cssWidth: number,
): number {
  return isExport ? renderWidth / EXPORT_REFERENCE_WIDTH_PX : renderWidth / cssWidth;
}
