"""The title block is anchored to the sheet frame, not to a fraction of the sheet.

`render_bounds` is the ISO sheet inflated by 1.1, so its margin grows with paper size. Fractions of
it are the right frame for a zone box and the wrong one for a field: dividing by that denominator
made one drawing template read as several. Measured from a sheet corner the A3 sheets agree to 0.00.

Observations come from `tests/fixtures/title_block/anchor_observations.json`, regenerated by
`tools/title_block_anchors.py --write-fixture`. The fixture holds observations only; every rule that
turns them into an anchor lives here, so a rule change is a reviewable diff.

`test_absolute_offsets_agree_where_fractions_do_not` is the one that matters -- a fraction table
would pass all the others, so the comparison is pinned rather than only the result.

See `06 - .../Gotcha - One Template Looked Like Several in Fraction Space.md` in the vault.
"""

from __future__ import annotations

import json
import statistics as st
from collections import defaultdict
from pathlib import Path

import pytest

FIXTURE = Path(__file__).parent / "fixtures" / "title_block" / "anchor_observations.json"

# `render_bounds` is the sheet plus a 5% margin on every side. Pinned because the margin is what
# differs between paper sizes and therefore what breaks fraction-space comparison.
BOUNDS_INFLATION = 1.1

ISO_SHEETS = {"A0": (1189, 841), "A1": (841, 594), "A2": (594, 420), "A3": (420, 297)}

# The two title blocks. Measured, not declared: `tools/title_block_anchors.py` picks each field's
# corner by minimising spread, and these are what it picks.
UPPER_LEFT_FIELDS = {"unit_number", "part_number", "stock_quantity", "quantity"}
BOTTOM_FIELDS = {
    "machine_name",
    "line_name",
    "previous_drawing_number",
    "machine_unit_code",
    "drawn",
    "designed",
    "scale",
    "job_number",
    "creation_date",
}

# `creation_date` is the one bottom-block field that moves within a paper size. Listed rather than
# tolerated globally so that a second such field fails instead of hiding behind a loose bound.
KNOWN_UNSTABLE = {"creation_date"}

BOM_ROW_PITCH = 7.0

# Measured, in drawing units, keyed by `render_bounds` width because that is what an observation
# carries. The A2 frame sits 5.00 further in from the right, top and bottom sheet edges than the A3
# one and flush on the left. That it is an inset rather than a scale is what lets one template serve
# both sizes; `test_the_frame_inset_is_one_constant_per_paper_size` re-derives these from the
# observations, so they are pinned values rather than assumed ones.
FRAME_INSET = {462.0: 0.0, 653.4: 5.0}
FLUSH_EDGES = ("left",)


@pytest.fixture(scope="module")
def observations() -> list[dict]:
    assert FIXTURE.exists(), (
        f"Missing {FIXTURE}. Regenerate with:\n"
        "  services/backend/.venv/Scripts/python.exe tools/title_block_anchors.py --write-fixture"
    )
    rows = json.loads(FIXTURE.read_text(encoding="utf-8"))["observations"]
    assert rows, "Fixture holds no observations"
    return rows


def _by_feature(rows: list[dict], category: str) -> dict[str, list[dict]]:
    grouped = defaultdict(list)
    for row in rows:
        if row["category"] == category:
            grouped[row["feature"]].append(row)
    return grouped


def _sheet_offset(row: dict, edge: str) -> float:
    """The offset measured from the real sheet edge rather than from the inflated bounds.

    The margin is half the inflation of the axis being measured, so a `top`/`bottom` edge takes
    the height and a `left`/`right` edge takes the width. Using one for the other is a constant
    error per paper size, which survives a same-size comparison and only shows up across sizes.
    """
    extent = row["bounds_height"] if edge in ("top", "bottom") else row["bounds_width"]
    return row["offsets"][edge] - extent * (1 - 1 / BOUNDS_INFLATION) / 2


def _frame_offset(row: dict, edge: str) -> float:
    """The offset from the drawing frame, which is what the fields are actually placed against."""
    width = row["bounds_width"]
    assert width in FRAME_INSET, (
        f"No frame inset pinned for render_bounds width {width}. The corpus gained a paper size; "
        "measure its inset and add it to FRAME_INSET rather than loosening a tolerance."
    )
    inset = 0.0 if edge in FLUSH_EDGES else FRAME_INSET[width]
    return _sheet_offset(row, edge) - inset


def test_render_bounds_is_the_iso_sheet_inflated_by_one_point_one(observations) -> None:
    """The premise the rest of this file rests on, and the reason fractions do not transfer."""
    sizes = {(row["bounds_width"], row["bounds_height"]) for row in observations}
    for width, height in sizes:
        sheet = (width / BOUNDS_INFLATION, height / BOUNDS_INFLATION)
        assert any(
            abs(sheet[0] - w) < 0.5 and abs(sheet[1] - h) < 0.5 for w, h in ISO_SHEETS.values()
        ), (
            f"render_bounds {width} x {height} implies sheet {sheet[0]:.1f} x {sheet[1]:.1f}, "
            f"which is not an ISO size at inflation {BOUNDS_INFLATION}."
        )


def test_title_block_fields_are_fixed_within_a_paper_size(observations) -> None:
    """Against its own corner, a field does not move between sheets of the same size."""
    moved = {}
    for feature, rows in _by_feature(observations, "title_block").items():
        if feature in KNOWN_UNSTABLE:
            continue
        x_edge = "left" if feature in UPPER_LEFT_FIELDS else "right"
        y_edge = "top" if feature in UPPER_LEFT_FIELDS else "bottom"
        for edge in (x_edge, y_edge):
            per_size = defaultdict(list)
            for row in rows:
                per_size[row["bounds_width"]].append(row["offsets"][edge])
            for width, values in per_size.items():
                if len(values) > 1 and st.pstdev(values) > 0.25:
                    moved[(feature, edge, width)] = round(st.pstdev(values), 2)
    assert not moved, (
        "These title-block fields move between sheets of one paper size, so they are not "
        f"frame-anchored: {moved}. Either the corpus gained a second template, or a marking is "
        "misplaced -- check for a retracted correction before widening the bound."
    )


def test_the_two_title_blocks_anchor_to_different_corners(observations) -> None:
    """Pooling them is what made the category read as unstable while every field was fixed."""
    grouped = _by_feature(observations, "title_block")
    for feature, rows in grouped.items():
        if len(rows) < 4:
            continue
        expected_y = "top" if feature in UPPER_LEFT_FIELDS else "bottom"
        other_y = "bottom" if expected_y == "top" else "top"
        assert st.pstdev([r["offsets"][expected_y] for r in rows]) <= st.pstdev(
            [r["offsets"][other_y] for r in rows]
        ), (
            f"{feature} sits at a more fixed distance from the {other_y} edge than the "
            f"{expected_y} one, so it is anchored to the other block's corner"
        )

    upper = {f for f in grouped if f in UPPER_LEFT_FIELDS}
    bottom = {f for f in grouped if f in BOTTOM_FIELDS}
    assert upper and bottom, (
        "The corpus no longer covers both title blocks. This test cannot detect the pooling "
        f"mistake it exists for. upper={sorted(upper)} bottom={sorted(bottom)}"
    )


def test_absolute_offsets_agree_where_fractions_do_not(observations) -> None:
    """The trap itself. A fraction table would pass every other test in this file."""
    compared = 0
    for feature, rows in _by_feature(observations, "title_block").items():
        if feature in KNOWN_UNSTABLE or len({r["bounds_width"] for r in rows}) < 2:
            continue
        edge = "top" if feature in UPPER_LEFT_FIELDS else "bottom"
        frame_sd = st.pstdev([_frame_offset(row, edge) for row in rows])
        # The same quantity in drawing units, so the two spreads are directly comparable.
        fraction_sd_units = st.pstdev([row["fraction"]["fy"] for row in rows]) * st.mean(
            [r["bounds_height"] for r in rows]
        )
        assert frame_sd < fraction_sd_units, (
            f"{feature}: fraction space is no worse than frame space here "
            f"({fraction_sd_units:.2f} vs {frame_sd:.2f} units). If that is real, this corpus "
            "stopped mixing paper sizes and the test has lost its subject."
        )
        assert frame_sd < 0.25, (
            f"{feature} is not fixed against the frame across paper sizes (sd {frame_sd:.2f})."
        )
        compared += 1
    assert compared, "No title-block field appears at two paper sizes; the trap is untested."


def test_the_frame_inset_is_one_constant_per_paper_size(observations) -> None:
    """A2 differs from A3 by a frame inset, not by a scale factor. A scale would spread these."""
    deltas = {}
    for feature, rows in _by_feature(observations, "title_block").items():
        if feature in KNOWN_UNSTABLE or feature in UPPER_LEFT_FIELDS:
            continue
        per_size = defaultdict(list)
        for row in rows:
            per_size[row["bounds_width"]].append(_sheet_offset(row, "bottom"))
        if len(per_size) < 2:
            continue
        sizes = sorted(per_size)
        deltas[feature] = st.mean(per_size[sizes[-1]]) - st.mean(per_size[sizes[0]])
    assert deltas, "No bottom-block field spans two paper sizes."
    assert st.pstdev(list(deltas.values())) < 0.25, (
        f"The A2-A3 offset is not one constant across bottom-block fields: {deltas}. "
        "A varying delta means the template scales with paper size rather than being inset."
    )
    measured = st.mean(list(deltas.values()))
    pinned = FRAME_INSET[653.4] - FRAME_INSET[462.0]
    assert abs(measured - pinned) < 0.25, (
        f"The A2 frame inset measured {measured:.2f}, pinned at {pinned}. Update FRAME_INSET from "
        "the observations rather than widening this bound."
    )


def test_bom_rows_are_evenly_pitched(observations) -> None:
    """A BOM with N items is one pitch, not N unknowns. Optional columns do not move the rows."""
    per_sheet = defaultdict(set)
    for row in observations:
        if row["category"] == "bill_of_materials":
            per_sheet[(row["drawing_id"], row["bounds_width"])].add(round(row["offsets"]["top"], 2))
    multi = [sorted(levels) for levels in per_sheet.values() if len(levels) > 2]
    assert multi, "No sheet in the corpus has a multi-row BOM; the pitch is unmeasured."
    for levels in multi:
        gaps = [round(b - a, 2) for a, b in zip(levels, levels[1:], strict=False)]
        assert all(abs(gap - BOM_ROW_PITCH) < 0.25 for gap in gaps), (
            f"BOM row gaps {gaps} are not the pinned pitch {BOM_ROW_PITCH}."
        )
