from datetime import datetime, timezone, UTC
from typing import Optional, List
from beanie import Document
from pydantic import Field

class AuditFeedbackDocument(Document):
    """
    Persists human engineer feedback events (dismissals, corrections, category overrides)
    to drive active learning and auto-generate Obsidian Second Brain rule notes.
    """
    session_id: str = Field(..., description="Active audit comparison session ID")
    drawing_id: str = Field(..., description="Drawing ID this finding was attached to")
    client_name: Optional[str] = Field(None, description="Client name associated with the drawing room")
    entity_text: str = Field(..., description="Exact text content of the finding")
    entity_handle: Optional[str] = Field(None, description="CAD entity handle if available (e.g. 1B2A)")
    category: str = Field(..., description="Checklist category (e.g. drawing_views, title_block)")
    original_status: str = Field(..., description="Status generated by AI engine (e.g. CHANGED, REMOVED)")
    human_corrected_status: str = Field(..., description="Human override verb: dismissed, confirmed_valid, category_override, verdict_matched, verdict_changed, confirmed_change, value_correction")
    human_comment: Optional[str] = Field(None, description="Optional explanation or comment from human engineer")
    coordinates: Optional[List[float]] = Field(None, description="Physical CAD coordinate [x, y]")
    # Richer-correction fields (human-in-the-loop learning). corrected_* carry the human's
    # intended target; finding_snapshot is a fixed-shape feature dict (api.schemas.FindingSnapshot,
    # stored as a plain dict here to keep the domain model free of an api-layer import) that lets
    # the trainer rebuild the exact runtime feature vector for this correction later.
    corrected_category: Optional[str] = Field(None, description="Target category for a category_override correction")
    corrected_value: Optional[str] = Field(None, description="Corrected value for a value_correction")
    finding_snapshot: Optional[dict] = Field(None, description="Feature snapshot of the corrected finding for model training")
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    class Settings:
        name = "audit_feedback"
        indexes = [
            "session_id",
            "drawing_id",
            "client_name",
            "entity_text",
            "human_corrected_status",
        ]
