from datetime import datetime, timezone, UTC
from typing import Optional, List
from beanie import Document
from pydantic import Field

class AuditFeedbackDocument(Document):
    """
    Persists human engineer feedback events (dismissals, corrections, category overrides)
    to drive active learning and auto-generate Obsidian Second Brain rule notes.
    """
    session_id: str = Field(..., description="Active audit comparison session ID")
    drawing_id: str = Field(..., description="Drawing ID this finding was attached to")
    client_name: Optional[str] = Field(None, description="Client name associated with the drawing room")
    entity_text: str = Field(..., description="Exact text content of the finding")
    entity_handle: Optional[str] = Field(None, description="CAD entity handle if available (e.g. 1B2A)")
    category: str = Field(..., description="Checklist category (e.g. drawing_views, title_block)")
    original_status: str = Field(..., description="Status generated by AI engine (e.g. CHANGED, REMOVED)")
    human_corrected_status: str = Field(..., description="Human override verb: dismissed, confirmed_valid, category_override, verdict_matched, verdict_changed, confirmed_change, value_correction")
    human_comment: Optional[str] = Field(None, description="Optional explanation or comment from human engineer")
    coordinates: Optional[List[float]] = Field(None, description="Physical CAD coordinate [x, y]")
    # Richer-correction fields (human-in-the-loop learning). corrected_* carry the human's
    # intended target; finding_snapshot is a fixed-shape feature dict (api.schemas.FindingSnapshot,
    # stored as a plain dict here to keep the domain model free of an api-layer import) that lets
    # the trainer rebuild the exact runtime feature vector for this correction later.
    corrected_category: Optional[str] = Field(None, description="Target category for a category_override correction")
    corrected_value: Optional[str] = Field(None, description="Corrected value for a value_correction")
    #: WHICH entity the engine should have paired with, for a `mispaired_*` correction.
    #:
    #: The field that makes matcher feedback trainable at all. Measured 2026-08-19: of 106
    #: `mispaired_*` rows, **3** carried the counterpart -- it was an optional free-text box and
    #: was rationally skipped. The other 103 record a rejection with no correction, and a matcher
    #: cannot be trained on negatives: there is no target to learn toward. Those rows are not
    #: recoverable, which is why the capture had to change rather than the analysis.
    #:
    #: Shape: `{"side": "ref"|"rev", "handle": str|None, "text": str, "coordinates": [x, y]}`.
    #: `handle` is null for block-exploded content, which is the normal case on a reference
    #: sheet, so the text and coordinate are not redundant padding -- they are how such an
    #: entity is identified at all.
    #:
    #: Optional and defaulting to null: the 249 rows written before 2026-08-19 stay valid and
    #: unmigrated. A trainer reading this must treat absence as "not recorded", never as "no
    #: counterpart exists".
    corrected_counterpart: Optional[dict] = Field(
        None, description="Entity the engine should have paired with, for a mispaired_* correction"
    )
    finding_snapshot: Optional[dict] = Field(None, description="Feature snapshot of the corrected finding for model training")
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    # Retraction, for a correction clicked by mistake. Set rather than deleted: this collection
    # is the training corpus AND the audit trail of who taught the model what, and a row that
    # silently vanishes is unauditable.
    #
    # A compensating record was the obvious alternative — `confirmed_valid` already exists as
    # "undo of a dismissal" — but it is wrong for training. `train_from_feedback` sorts by
    # `created_at`, so a later record does win the exact-match override; the *classifier* rows,
    # though, are appended per document, so an undone correction would contribute two rows with
    # identical features and opposite labels. At 33 labels that is expensive noise. A retracted
    # document is skipped by the trainer entirely.
    retracted_at: Optional[datetime] = Field(
        None, description="When a human took this correction back. Non-null rows never train."
    )

    class Settings:
        name = "audit_feedback"
        indexes = [
            "session_id",
            "drawing_id",
            "client_name",
            "entity_text",
            "human_corrected_status",
        ]
