"""The hand-labelled `(query -> relevant chunk)` set, and the rules that keep it honest.

Mirrors the discipline `infrastructure/eval/corpus.py` established for the comparison corpus,
because the same three ways of quietly invalidating a label set apply here:

1. **Corpus drift.** A label names a chunk id. Rebuild the index from changed sources and those
   ids can move, at which point every label silently points at the wrong text — or at nothing,
   which scores as a miss and looks like the encoder got worse. Each label set records the
   `source_digest` of the index it was authored against and **refuses to score on a mismatch**.
2. **Guideline version.** If the rule for "what counts as relevant" changes, existing labels were
   authored under a different question. Labels carry the guideline version and are rejected on
   mismatch rather than silently mixed.
3. **Provenance.** A label written by a human and a label generated by a script are not the same
   evidence, and the difference disappears the moment they share a file. `provenance` is required
   on every label, and `synthetic` labels are **excluded from the scored set by default**.

Point 3 is the one this file exists for. It is trivially easy to generate labels by taking a
chunk, using its own heading as the query, and declaring that chunk relevant — and the resulting
`recall@5` would be near 1.00 and would mean nothing, because it measures whether TF-IDF can find
the document a string was copied out of. That is the retrieval-shaped version of the mutation-pair
limit [[ADR-007 Re-scoping the Maturity Ladder]] already ruled inadmissible on the comparison
track. Synthetic labels are useful as a smoke test — they catch a totally broken index — and are
not evidence about retrieval quality. The type system says so here so that nobody has to remember.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Any

from .metrics import LabelledQuery

#: Tracks the `date:` frontmatter of the retrieval annotation guideline. Bump when the definition
#: of "relevant" changes; labels authored under an older version are refused, not migrated.
#:
#: 2026-08-07: initial. Relevance = "a checker auditing a drawing that raised this query would
#: want this clause shown to them". Judged per (query, chunk) pair, not per document.
GUIDELINE_VERSION = "2026-08-07"

LABEL_SCHEMA_VERSION = 1


class Provenance(StrEnum):
    HUMAN = "human"          # a person read the chunk and judged it relevant
    SYNTHETIC = "synthetic"  # generated from the corpus; a smoke test, never evidence


class LabelError(RuntimeError):
    """A label set is malformed, stale, or authored under a different guideline."""


class LabelDriftError(LabelError):
    """The index no longer matches the corpus these labels were authored against."""


@dataclass(frozen=True)
class RetrievalLabel:
    query_id: str
    query: str
    relevant_ids: list[str]
    provenance: Provenance
    note: str = ""

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["provenance"] = str(self.provenance)
        return payload

    @classmethod
    def from_dict(cls, raw: dict[str, Any]) -> RetrievalLabel:
        missing = {"query_id", "query", "relevant_ids", "provenance"} - set(raw)
        if missing:
            raise LabelError(f"Label is missing required field(s): {sorted(missing)}")
        try:
            provenance = Provenance(raw["provenance"])
        except ValueError as err:
            raise LabelError(
                f"Label {raw['query_id']!r} has provenance {raw['provenance']!r}; expected one "
                f"of {[str(p) for p in Provenance]}. Provenance is required because a generated "
                f"label and a human judgement are not the same evidence."
            ) from err
        if not raw["relevant_ids"]:
            raise LabelError(
                f"Label {raw['query_id']!r} names no relevant chunk. If nothing in the corpus "
                f"answers the query, that is a coverage finding — record it in `unanswerable`, "
                f"not as a scored label with no correct answer."
            )
        return cls(
            query_id=raw["query_id"],
            query=raw["query"],
            relevant_ids=list(raw["relevant_ids"]),
            provenance=provenance,
            note=raw.get("note", ""),
        )


@dataclass(frozen=True)
class LabelSet:
    collection: str
    guideline_version: str
    source_digest: str
    labels: list[RetrievalLabel] = field(default_factory=list)
    #: Queries a human judged that *nothing* in the corpus answers. Not scored, but recorded:
    #: they are the coverage story, and a corpus that cannot answer real questions is a finding
    #: no recall number will surface.
    unanswerable: list[str] = field(default_factory=list)
    schema_version: int = LABEL_SCHEMA_VERSION

    def human_labels(self) -> list[RetrievalLabel]:
        return [label for label in self.labels if label.provenance is Provenance.HUMAN]

    def scored(self, include_synthetic: bool = False) -> list[LabelledQuery]:
        """The labels that may contribute to a reported metric.

        Human-only by default. Passing `include_synthetic=True` is legitimate for a smoke test
        and must never be used to populate a published baseline.
        """
        chosen = self.labels if include_synthetic else self.human_labels()
        return [
            LabelledQuery(
                query_id=label.query_id,
                query=label.query,
                relevant_ids=frozenset(label.relevant_ids),
                note=label.note,
            )
            for label in chosen
        ]

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "collection": self.collection,
            "guideline_version": self.guideline_version,
            "source_digest": self.source_digest,
            "labels": [label.to_dict() for label in self.labels],
            "unanswerable": list(self.unanswerable),
        }

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(self.to_dict(), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    @classmethod
    def load(cls, path: Path) -> LabelSet:
        if not path.exists():
            raise LabelError(f"No label set at {path}.")
        raw = json.loads(path.read_text(encoding="utf-8"))

        if raw.get("schema_version") != LABEL_SCHEMA_VERSION:
            raise LabelError(
                f"Label set at {path} has schema_version {raw.get('schema_version')!r}; this "
                f"build expects {LABEL_SCHEMA_VERSION}."
            )
        if raw.get("guideline_version") != GUIDELINE_VERSION:
            raise LabelError(
                f"Label set at {path} was authored under guideline "
                f"{raw.get('guideline_version')!r}, but the active guideline is "
                f"{GUIDELINE_VERSION!r}. Relevance was defined differently — re-label the "
                f"affected queries or discard them. Do not mix."
            )
        return cls(
            collection=raw["collection"],
            guideline_version=raw["guideline_version"],
            source_digest=raw.get("source_digest", ""),
            labels=[RetrievalLabel.from_dict(item) for item in raw.get("labels", [])],
            unanswerable=list(raw.get("unanswerable", [])),
        )

    def assert_matches_index(self, index_digest: str) -> None:
        """Refuse to score against a corpus these labels were not authored against.

        A stale label points at a chunk id that has moved or vanished. That scores as a miss, so
        the failure presents as *"retrieval got worse"* — the most misleading shape a measurement
        bug can take, because it invites you to go fix the encoder.
        """
        if not self.source_digest:
            return  # authored before a digest was recorded; caller decides
        if index_digest and self.source_digest != index_digest:
            raise LabelDriftError(
                f"Labels for '{self.collection}' were authored against corpus "
                f"{self.source_digest[:23]}..., but the index now holds "
                f"{index_digest[:23]}.... Chunk ids may have moved, in which case every label "
                f"silently points at the wrong text and scores as a miss — which looks exactly "
                f"like the encoder regressing. Re-label, or rebuild the index from the original "
                f"sources."
            )


def default_labels_path(collection: str) -> Path:
    repo_root = Path(__file__).resolve().parents[4]
    return repo_root / "tests" / "fixtures" / "retrieval" / f"labels-{collection}.json"


def default_baseline_path() -> Path:
    repo_root = Path(__file__).resolve().parents[4]
    return repo_root / "tests" / "fixtures" / "retrieval" / "retrieval-baseline.json"
