#!/usr/bin/env python
"""Re-address corpus labels after a re-export, by unique text match. Never by guess.

    services/backend/.venv/Scripts/python.exe tools/migrate_label_addresses.py
    ... tools/migrate_label_addresses.py --pair-id M745227N01
    ... tools/migrate_label_addresses.py --write

## Why this exists

A label addresses its entity one of two ways (`ExpectedFinding`):

* `REV-1B2A` -- a DXF handle. Survives a re-extraction: it comes from the file.
* `REV#412`  -- line 412 of the frozen entity payload. Does NOT survive. The payload is
  regenerated by a re-export and every line may move.

Measured 2026-08-19 across the four labelled pairs: 33 of 57 findings are payload-addressed
(58%). Re-exporting the corpus -- which is needed, because ten of eleven pairs are still on
extraction `schema_v=2` while the extractor is on 7 -- invalidates every one of them. Without
this tool that is 33 findings to re-label by hand, which is most of the annotation work done so
far and the reason the upgrade keeps not happening.

## How a broken address is repaired

Each finding carries the TEXT it was recorded against (`ref_text` / `rev_text`). That text is
looked up in the NEW payload for the same side. Exactly one match rewrites the address. Anything
else -- no match, or more than one -- is reported and left alone.

Unique-or-nothing, always. A label pointed at the wrong line still SCORES: it is compared
against an entity nobody looked at, and the recall figure it produces is wrong with no symptom.
A missing label is a visible gap; a mis-addressed one is an invisible lie, so ambiguity must be
a refusal rather than a best guess.

Handle-addressed findings are verified too, not assumed. "Handles survive re-extraction" is a
claim about ezdxf and about block explosion, and this reports any that stopped resolving rather
than trusting it.

## Order of operations

Run this AFTER the re-export, never before: it reads the new payload. The old one is gone by
then, which is fine -- the repair uses the label's own recorded text, not the old payload.

    1. git commit                       # labels are tracked; this is the restore point
    2. eval_corpus.py export ...        # re-export the pair(s)
    3. tools/migrate_label_addresses.py # report
    4. ... --write                      # apply
    5. eval_corpus.py verify            # digests + offline readiness
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(errors="replace")
    except (AttributeError, OSError):
        pass

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from services.backend.infrastructure.eval.corpus import (  # noqa: E402
    ExpectedFinding,
    default_fixtures_dir,
    default_payload_dir,
    read_manifest,
)


def entity_text(entity: dict[str, Any]) -> str:
    """The text an entity carries, from either place the payload puts it."""
    props = entity.get("properties") or {}
    geo = entity.get("geometry") or {}
    return str(props.get("text") or geo.get("text") or "").strip()


def entity_handle(entity: dict[str, Any]) -> str:
    """A dict-aware handle read.

    `ExpectedFinding.resolve` uses `getattr`, which silently returns nothing for the plain dicts
    a JSONL payload loads as -- so a handle address would look unresolvable for every finding.
    The address PARSER is reused (`ExpectedFinding.address`); only the lookup is restated here,
    against the shape actually on disk.
    """
    props = entity.get("properties") or {}
    return str(entity.get("handle") or props.get("handle") or "")


def read_entities(pair_dir: Path, side: str) -> list[dict[str, Any]]:
    path = pair_dir / f"{side}.entities.jsonl"
    if not path.exists():
        raise SystemExit(f"{path} does not exist - re-export the pair first.")
    with path.open(encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def repair(
    finding: dict[str, Any],
    ref_entities: list[dict[str, Any]],
    rev_entities: list[dict[str, Any]],
) -> tuple[str, str]:
    """`(outcome, detail)` for one finding. Outcome is `ok`, `rewritten`, or `unresolved`.

    Pure, so every branch is testable without a corpus on disk.
    """
    parsed = ExpectedFinding.from_dict(finding)
    side, kind, value = parsed.address
    entities = ref_entities if side == "REF" else rev_entities
    recorded = (parsed.ref_text if side == "REF" else parsed.rev_text).strip()

    if kind == "handle":
        # Verified, not assumed. If a handle stopped resolving, the claim that handles survive
        # a re-extraction is false for this entity and somebody needs to know.
        if any(entity_handle(e) == value for e in entities):
            return "ok", f"{parsed.qualified_handle}"
        return "unresolved", f"{parsed.qualified_handle}  handle no longer in the payload"

    index = int(value)
    # Still correct? A re-export often moves most lines but not all, and rewriting an address
    # that already points at the right entity would be churn with a chance of being wrong.
    if 0 <= index < len(entities) and recorded and entity_text(entities[index]) == recorded:
        return "ok", f"{parsed.qualified_handle}  still correct"

    if not recorded:
        return "unresolved", f"{parsed.qualified_handle}  label records no text for this side"

    hits = [i for i, e in enumerate(entities) if entity_text(e) == recorded]
    if len(hits) == 1:
        finding["entity_handle"] = f"{side}#{hits[0]}"
        return "rewritten", f"{parsed.qualified_handle} -> {side}#{hits[0]}   {recorded[:32]}"
    if not hits:
        return "unresolved", f"{parsed.qualified_handle}  no entity carries {recorded[:32]!r}"
    return (
        "unresolved",
        f"{parsed.qualified_handle}  {len(hits)} entities carry {recorded[:32]!r} - ambiguous",
    )


def migrate_pair(labels: dict[str, Any], pair_dir: Path) -> dict[str, list[str]]:
    """Repair every finding in one pair's labels, in place. Returns outcomes by kind."""
    ref_entities = read_entities(pair_dir, "ref")
    rev_entities = read_entities(pair_dir, "rev")
    out: dict[str, list[str]] = {"ok": [], "rewritten": [], "unresolved": []}
    for finding in labels.get("findings") or []:
        outcome, detail = repair(finding, ref_entities, rev_entities)
        out[outcome].append(detail)
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--pair-id", help="one pair; default is every labelled pair")
    ap.add_argument("--write", action="store_true", help="apply the rewrites (default: report)")
    args = ap.parse_args(argv)

    base = default_fixtures_dir()
    manifest = read_manifest()
    totals = {"ok": 0, "rewritten": 0, "unresolved": 0}
    touched: list[tuple[Path, dict[str, Any]]] = []

    for pair in manifest.get("pairs") or []:
        pair_id = pair.get("pair_id")
        if args.pair_id and pair_id != args.pair_id:
            continue
        rel = pair.get("labels")
        if not isinstance(rel, str):
            continue
        label_path = base / rel
        if not label_path.exists():
            continue
        labels = json.loads(label_path.read_text(encoding="utf-8"))
        if not (labels.get("findings") or []):
            continue

        result = migrate_pair(labels, default_payload_dir() / pair_id)
        for key in totals:
            totals[key] += len(result[key])

        print(f"\n{pair_id}: {len(labels['findings'])} finding(s)")
        print(f"   ok {len(result['ok'])}   rewritten {len(result['rewritten'])}   "
              f"unresolved {len(result['unresolved'])}")
        for detail in result["rewritten"]:
            print(f"     [rewrite] {detail}")
        for detail in result["unresolved"]:
            print(f"     [!]       {detail}")
        if result["rewritten"]:
            touched.append((label_path, labels))

    print(
        f"\ntotal: {totals['ok']} unchanged, {totals['rewritten']} rewritten, "
        f"{totals['unresolved']} unresolved"
    )
    if totals["unresolved"]:
        print("  Unresolved labels are LEFT ALONE and must be re-addressed by hand. A label")
        print("  pointed at the wrong entity still scores, so nothing here is guessed.")

    if not args.write:
        print("\n[dry-run] nothing written. Re-run with --write to apply.")
        return 0

    for path, labels in touched:
        path.write_text(json.dumps(labels, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"[done] wrote {path}")
    print("[next] tools/eval_corpus.py verify")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
